### ISSUE TITLE
How does this compare to http://image.intervention.io/

### ISSUE THREAD

**Issue by AndreasHeiberg** [kosinix/grafika#2]
Not to discourage this great effort. Just curious.

**Comment by kosinix** [comment]
Hi @AndreasHeiberg ,

Thank your interest. Sorry for the late response. I was busy implementing the GIF support for GD in the last few days. FYI I have updated the [Why Grafika? ](http://kosinix.github.io/grafika/index.html) section here.  But to answer your question:

- Smart crop - Grafika can guess the best crop position wherein the most interesting part of the image is preserved. Intervention has manual crop positions only. It can also do all crop positions that Imagine have along with an offset.
- Animated GIF support - Grafika can resize animated GIF on both GD and Imagick. Intervention can only do that on Imagick. Grafika has its own GIF decoder/encoder (in PHP) to be able to do this on GD while Intervention is just a thin wrapper on top of GD/Imagick.
- Image compare - Grafika can compare images. I dont think Intervention can do that.
- Advance Filters - Sobel and Floyd-Steinberg Dithering. These are the same image processing filters use in other languages.
- Emphasis on resizing - Resize functions are more prominent with their own function names. resizeFit, resizeFill, resizeExact, resizeExactWidth, and resizeExactHeight or use the generic resize api.
- Bezier curves on GD. I am not sure if Intervention supports bezier curves perhaps on Imagick only since Imagick has native bezier support.

There are also a lot of overlapping functions too such as basic filters. Grafika supports all the basic filters that Intervention has. Method chaining too.

As for functionalities that Intervention has that Grafika is missing:

- Basic transform functions (flip vert, horz). This are easy additions and will be in future releases of Grafika.
- exif info
- Image as HTTP responses - I have no plan on supporting this as Im sticking with filesystem i/o operations for images

Those are the stuff that I am aware of as I am not fully familiar with Interventions entire API.

**Comment by AndreasHeiberg** [comment]
Cool sounds like you're doing a fair bit differently :) 

> Image compare - Grafika can compare images. I dont think Intervention can do that.

I actually sent a PR to Intervention for that recently, so in due time it should.
